export const pendingDoctorsMock = [
  {
    id: 101,
    firstName: "Anna",
    lastName: "Petrova",
    email: "anna.petrova@example.com",
    specialization: "Кардиолог",
    experience: "",
    isApproved: false,
    createdAt: "2024-05-01",
    status: "непотвърден",
    roles: ["DOCTOR"],
  },
  {
    id: 102,
    firstName: "Ivan",
    lastName: "Ivanov",
    email: "ivan.ivanov@example.com",
    specialization: "Невролог",
    experience: "",
    isApproved: false,
    createdAt: "2024-05-03",
    status: "непотвърден",
    roles: ["DOCTOR"],
  },
  {
    id: 103,
    firstName: "Maria",
    lastName: "Dimitrova",
    email: "maria.dimitrova@example.com",
    specialization: "Педиатър",
    experience: "",
    isApproved: false,
    createdAt: "2024-05-05",
    status: "непотвърден",
    roles: ["DOCTOR"],
  },
];
